name = "nobis-platform"
main = "src/index.js"
compatibility_date = "2026-01-06"

# 1. This connects the Worker to the domain (No path allowed here)
[[build.upload]]
format = "modules"

[env.production]
routes = [
	{ pattern = "joshwidby.com/nobis*", zone_name = "joshwidby.com" }
]

# 2. Serve the React build folder
[assets]
directory = "./build"
not_found_handling = "single-page-application"

# 3. Connect your D1 Database (Use your actual ID)
[[d1_databases]]
binding = "DB"
database_name = "nobis-db"
database_id = "34a18bc3-fbb6-4ad9-941c-39d246c8637e"